# This is a basic workflow to help you get started with Actions

name: Test cargo-binstall on crate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Reduce permissions to minimum
permissions:
  # To fetch code
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test using cargo-binstall to install a Rust crate from a repository
  test-binstall:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install cargo-binstall
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      # Install HCML
      - name: Install HCML
        run: cargo binstall --git="https://github.com/abclop99/hcml" hcml

      # Run HCML to prove it exists and works
      - name: Run HCML
        run: hcml

      # Run HCML help
      - name: Run HCML help
        run: hcml --help
